server:
  port: ${PORT:8083}
  forward-headers-strategy: native

spring:
  application:
    name: food-qr-monolith
  
  data:
    mongodb:
      uri: ${MONGODB_URI1:mongodb+srv://restrofoodiescanner_db_user:p6g4IAduGwk2t5To@pranav001.8l3iyj8.mongodb.net/food_qr_db?retryWrites=true&w=majority&maxPoolSize=50}
    redis:
      url: ${REDIS_URL:rediss://dineval-siys3c.serverless.aps1.cache.amazonaws.com:6379}
      client-type: jedis
      timeout: 50s
      jedis:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 2

  mail:
    host: smtp.gmail.com
    port: 587
    username: restrofoodiescanner@gmail.com
    password: ${MAIL_PASSWORD:timq oecf lcnu hfro}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

resend:
  from-email: restrofoodiescanner@gmail.com

app:
  frontend :
    url : ${CUSTOMER_FRONTEND_URL:https://qr.dinesphere.co/qr?qrId=}

  qr:
    secret: ${APP_QR_SECRET:TnsLD53NKeFsHhZ73ojREN9XLT8dIuuvmeSh/f3FU2KF7q4m11nf/PJivEuplO9U4tZDUW0JPPByW2VHOU2HMQ==}
    token_ttl_seconds: 600
  session:
    secret: ${APP_SESSION_SECRET:mysupersecuresecretkey1234567890!!!}
    ttl-seconds: 21600
    token-ttl-seconds: 1800
  maintenance:
    secret: ${MAINTENANCE_SECRET:secure-maintenance-key-123}

jwt:
  issuer: festora-auth
  audience: festora-internal
  access-token-ttl-minutes: 15
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv7XcyPyxL/Lyj+5m2nW8
    9FUtT/4NMyAos+Qr360UQGlXF+bR0gXErDo/6CNCnMZyfqbeE4Z2dfoyekRBwBS3
    mHsQGSgXphJnJlVewj6nniWxwIsaSgFxizryLGW7QlRno5F3slgDy+/3VJYruCDR
    7aZgPMVTcG6drhXOdD+zarHns3+9X3CzWD5eu4b9pQOv/J/VqyRjJ2JOSy9jqtJk
    Q2hF/cs2zGjCIJwclEL8q9CiBQyAgxuTk8wb0SHcbPgcV7NRhY6q4G5wpwGxZgqR
    yhUtS/SxoeFLkuLUf0gVryhklIJM3yEP4UzTj3hyI+dwJpJm3150eyMI1zFyokJ+
    swIDAQAB
    -----END PUBLIC KEY-----
  private-key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC/tdzI/LEv8vKP
    7mbadbz0VS1P/g0zICiz5CvfrRRAaVcX5tHSBcSsOj/oI0KcxnJ+pt4ThnZ1+jJ6
    REHAFLeYexAZKBemEmcmVV7CPqeeJbHAixpKAXGLOvIsZbtCVGejkXeyWAPL7/dU
    liu4INHtpmA8xVNwbp2uFc50P7Nqseezf71fcLNYPl67hv2lA6/8n9WrJGMnYk5L
    L2Oq0mRDaEX9yzbMaMIgnByUQvyr0KIFDICDG5OTzBvRIdxs+BxXs1GFjqrgbnCn
    AbFmCpHKFS1L9LGh4UuS4tR/SBWvKGSUgkzfIQ/hTNOPeHIj53AmkmbfXnR7IwjX
    MXKiQn6zAgMBAAECggEAPmk+1OHK71C43dmfe1xcJPD73PBYrL258oKEM//dOXDx
    zRK0WRrOocEe3/xmqbJDQO8jGhkqxJKszzgcbaNw97+MiJwQQtz33rdpL3SFTgt4
    eDXw24nnxItunryJv3jJ+qqXXKShq8lV7CAtYHay0Rradr5IwTAJvkxUF21LhB6R
    NuV0kkUuzzz27jY6dJlP5Ev+gDF5nvIxYQMEieK6+zi7NU8nf514otU7l2QO/atx
    H5/ohyeGf1V+By1zmZluuj5dfhWLeYk6g0zeEm4/66EuEJYEJwDID4Gxaj3T0laY
    SxuUnaC+BGRuFGZXK6wwbOd1AYvMjUrTnO/liwmDYQKBgQDtkIPt4L4Uc/OyzDZj
    fUxw2QyvfqsPtnY5UFRqeJwOlUrR15pWI7hBR2y3bcyxKUzaRVXBpHYyYoyoYK7P
    3/ifSRr+MytbjcCNR3n8vETM72T5qvGP0TtkQSuyYPnLTNyf8s77lag6qMODQO8a
    TAzbtf1UjD7XH+rSEbxgrYuxoQKBgQDOlmdkWV3RfdfB3EhqwAHTPp8VltNOmb0A
    Nqun1u2kREiDHf9WP/DCgIcYWb46pI5dnOSb7bKmA1i9chl4AuEwCmyhC2cWuUdE
    nGa/IOeSQcAoYHzhgFdMftb5FVV1hgqVSDJyq83ApbbD8nPrIMi7ALN6QhNYQRZz
    VP4bxAW30wKBgQDUMpDVazj99fCJFcXDKkmcRxQAsglEOLvzR+CPVfo3QH0bYRUX
    ukI79PuUALykxnpCQUpvdGKrcMGpKOsc/TcLuHYm9zfUSJLk3yKEcPqXf4JXTK0G
    xGLjkx7f76VQRfCP4oely7D/7HzvAZJRj/qwSiflXHxJFdZfG76DMKEl4QKBgQC6
    a2ijWi1Z9Kg0zNYgVmGPQWwG7FKEFCFERxFBZKaPW/rfLruSFiLpMVg3Ngx+GK5L
    dV+qAaX7PvveAE9RR6/zTQTXklWVYN4Z4NSq1kOBbIm9JcyrJMgiRDczD/hNFAcK
    zNqRNc12cVNqoKfP3oakkS5kPan9MsbSjji7z3ildwKBgFv1fnJUz6C6ftzaygrN
    OHPTFZ6KnbWZUTvnQKJKGpdWZsbbsP8TIpu6Y8EeLZPhzR5i1PuLRx3i2ZyvvQ+Q
    avlsAEW0iAa9oxoC5CuThwz89tspWPqeMJwGmxVmWGZ71Q3rUtDOOOMXeWBLWRJ2
    3kKB+axGNif3btVLQFU5ThQR
    -----END PRIVATE KEY-----

# Menu / AWS Configs
supabase:
  endpoint: ${S3_ENDPOINT:https://jryaafvfzhnksekujawl.storage.supabase.co/storage/v1/s3}
  region: ${S3_REGION:ap-south-1}
  bucket: ${S3_NAME:images}
  access-key: ${ACCESS_KEY:60330f356bb38c7a65d120a4750f6e04}
  secret-key: ${SECRET_KEY:2878cd4cf1d0fb5e1b67643f3e4b40838ff13c1929c1526ec2fbf00bdd6726bb}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
    health:
      show-details: always

# Notification Service Configurations
telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME:dineSphereBot}
    token: ${TELEGRAM_BOT_TOKEN:8663859581:AAHCWDWczxzkiF5J5WO7wNwqHkLdjNi_AIY}

whatsapp:
  meta:
    token: ${WHATSAPP_META_TOKEN:EAA8cdDZAjJ4EBRmt1VXo4AedVrRlzDeeSAEABnzP7I8XhHixkcd9IBIlZBugXNvXwAPr2Lj4EZChHq0IiPKVPZAijQAQtoZBWL4MuZAqgZCr5ZAOdEfcHJyf4q9VDJ9pGIMThmgl5nZBusJEkj8TXrRv0EfsOZCNh9Mux0guoqFXWdmTPfsHzidZCyYueZBSZCzIvrZAPAOtJWRIyw9GqSgYofvapGxWdja8ZCAKlBBccESZB3og}
    phone-number-id: ${WHATSAPP_PHONE_NUMBER_ID:1184276304758930}
    verify-token: ${WHATSAPP_VERIFY_TOKEN:my-test-verify-token}

# Admin Notification (new signups, system alerts)
admin:
  notification:
    enabled: true
    whatsapp-phone: ${ADMIN_WHATSAPP_PHONE:919307712930}
    telegram-chat-id: ${ADMIN_TELEGRAM_CHAT_ID:-1003817357522}

