{
 "title": "DineSphere Spring Boot Observability",
 "tags": [
  "springboot",
  "observability"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Application Health Quick Stats", "type": "row", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"food-qr-monolith\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "System CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"food-qr-monolith\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "JVM Heap Memory Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"food-qr-monolith\",area=\"heap\"}",
     "legendFormat": "JVM Heap Used"
    }
   ]
  },
  {
   "title": "Throughput (Req/Sec)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"food-qr-monolith\"}[1m]))",
     "legendFormat": "Req/sec"
    }
   ]
  },
  { "title": "HTTP Network Traffic Details", "type": "row", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Average Response Latency per API Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"food-qr-monolith\"}[1m])) by (uri) / sum(rate(http_server_requests_seconds_count{application=\"food-qr-monolith\"}[1m])) by (uri) * 1000",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "HTTP Status Code Ingestion Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"food-qr-monolith\"}[1m])) by (status)",
     "legendFormat": "Status {{status}}"
    }
   ]
  },
  {
   "title": "Real-Time Application Logs (Grafana Loki)",
   "type": "row",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Live Application Log Stream",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{app=\"food-qr-monolith\"}"
    }
   ]
  }
 ]
}